### ISSUE TITLE
Google translation does not perform well

### ISSUE THREAD

**Issue by bmosseveld** [EHDEN/DrugMapping#1]
Now trying Amazon translation

**Comment by bmosseveld** [comment]
Results from Google to Amazon:

Source ingredients mapped total : from 1263 (63%) to 1446 (75%)
Source drugs with all ingredients mapped: from 3770 (65%) to 4679 (81%)
Total Source drugs mapped: from 1828 of 5777 (32%) to 2105 of 5777 (36%)
Total datacoverage drug mapping: from 4156179 of 10124354 (41%) to 4647332 of 10124354 (46%)

**Comment by PRijnbeek** [comment]
Nice to this has a good impact.

When you say Total Data Coverage this is not referring to only ingredients? 

<img width="597" alt="image" src="https://user-images.githubusercontent.com/7252105/66749520-604bf900-ee8a-11e9-9c62-a24e3c93280f.png">

What is the frequency percentage (sum up all as in table above which was 99.9% on ingredient)

**Comment by bmosseveld** [comment]
Total Data Coverage is referring to mapped GPK drugs:

Source drugs mapped to single CDM Clinical Drug: 18
Source drugs mapped to single CDM Clinical Drug Comp: 2086
Source drugs mapped to single CDM Clinical Drug Form: 1
Total Source drugs mapped: 2105 of 5777 (36%)

Datacoverage CDM Clinical Drug mapping: 41293 of 10124354 (0%)
Datacoverage CDM Clinical Drug Comp mapping: 4606022 of 10124354 (45%)
Datacoverage CDM Clinical Drug Form mapping: 17 of 10124354 (0%)
Total datacoverage drug mapping: 4647332 of 10124354 (46%)
