### ISSUE TITLE
Manual drug mappings don't overwrite automatically generated drug mappings

### ISSUE THREAD

**Issue by etirchalabi** [EHDEN/DrugMapping#12]
When I load optional file with manual drug mappings into drug mapping tool, and name the first column "SourceCode" and the second one "concept_id", .jar simply stops working at some point of process and freezes. 

Console log writes out the following:

[...]
2021-07-09 12:51:37     Loading manual drug mappings ...
Exception in thread "Thread-4" java.lang.RuntimeException: Field "SourceCode" not found
	at org.ohdsi.drugmapping.gui.files.DelimitedInputFileGUI.get(DelimitedInputFileGUI.java:173)
	at org.ohdsi.drugmapping.genericmapping.GenericMapping.getManualDrugMappings(GenericMapping.java:630)
	at org.ohdsi.drugmapping.genericmapping.GenericMapping.<init>(GenericMapping.java:363)
	at org.ohdsi.drugmapping.DrugMapping$MappingThread.run(DrugMapping.java:193)

When I delete names of columns and leave only values of SourceCodes and concept_id(s) .jar doesn't crash anymore, but its output files with drug mappings implies that it failed to overwrite drug mappings according to the file (it leaves mappings as the manual drug mapping file wasn't there).

**Comment by bmosseveld** [comment]
Hi,

Did you save you file settings to a file? If so could you please upload that settings file together with your manual drug mappings file?

**Comment by etirchalabi** [comment]
I did save file settings to a file.
Manual drug mappings file contains only two rows (first with name of the two columns, and second with a single manual map). Since it was written for the sake of testing process of overwriting in Drug Mapping Tool, source concept "Bedoxin" was manually mapped to "Metronidazole" (it actually IS incorrect mapping, but makes it easier to detect overwriting, than when correct mapping is used). 
[manualMap.zip](https://github.com/EHDEN/DrugMapping/files/6799392/manualMap.zip)

**Comment by bmosseveld** [comment]
It was a bug. I never used the option myself.
There is a new release (v0.0.3) where this bug is solved.
