### ISSUE TITLE
v0.0.3 is not starting

### ISSUE THREAD

**Issue by etirchalabi** [EHDEN/DrugMapping#13]
I am unable to execute DrugMapping v0.0.3 Executable Jar File.

It says:
Java Virtual Machine Launcher: "Error: A JNI error has ocurred, please check your installation and try again"

and after that:
Java Virtual Machine Launcher: "A Java Exception has occurred.".

**Comment by bmosseveld** [comment]
I have put a new zipfile in the release. It was compiled with the wrong version.
