### ISSUE TITLE
Jar and dat files missing

### ISSUE THREAD

**Issue by tas-you** [EHDEN/DrugMapping#15]
Hi, 
I downloaded the zip file and extracted it. I cannot find the .jar and .dat files there. Please help. 
Thanks

**Comment by bmosseveld** [comment]
Hi,
You probably downloaded the source.
You should download the DrugMapping-v1.0.1.zip file from the lates release:
https://github.com/EHDEN/DrugMapping/releases/download/v1.0.1/DrugMapping-v1.0.1.zip
That contains the .jar and .dat files.
